language: cpp

dist: trusty
sudo: required

git:
    depth: 3

before_install:
  - wget https://github.com/cpputest/cpputest/releases/download/v3.8/cpputest-3.8.tar.gz
  - tar xf cpputest-3.8.tar.gz
  - cd ./cpputest-3.8
  - CC=gcc-6 CXX=g++-6 ./configure --enable-std-cpp11 --prefix=/usr --disable-memory-leak-detection
  - make
  - sudo make install
  - cd ..

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-6.0
    packages:
      - g++-5
      - g++-6
      - g++-7
      - g++-8
      - clang-6.0

matrix:
  include:
    - os: linux
      compiler: gcc
      env: COMPILER=g++-5

    - os: linux
      compiler: gcc
      env: COMPILER=g++-6

    - os: linux
      compiler: gcc
      env: COMPILER=g++-7

    - os: linux
      compiler: gcc
      env: COMPILER=g++-8

    - os: linux
      compiler: clang
      env: COMPILER=clang++

script:
  - make CXX=$COMPILER
  - ./build/runtests
